### ISSUE TITLE
question - does yours lose registration?

### ISSUE THREAD

**Issue by Beej126** [lutz/VirtualDesktopNameDeskband#1]
after i get [mine ](https://github.com/Beej126/Win10VirtualDesktopDeskBand) registered with regasm and added to taskbar, it works happily for long time. but at some point, it will become unregistered saying that the clsid no longer exists or something like that. do you ever see this on yours?

**Comment by lutz** [comment]
No but after i start the pc today my deskband ist not loaded anymore. Currently i have not the time to look into it. Yesterday i test the SharpShell variant but now the virtual desktop api i use crashes. 👎

**Comment by lutz** [comment]
@Beej126 I updated the code with the updated virtual desktop api to version 1.7 [MScholtes](https://github.com/MScholtes/VirtualDesktop) and add the funktion for using <kbd>CTRL</kbd>+(<kbd>1</kbd>-<kbd>9</kbd>) to switch the vd. After recombiling with a new signing key it works also in correct way.

**Comment by Beej126** [comment]
that's cool... i remember i had a bug or two in virtual desktop so i had to
fix and embed that code directly

**Comment by lutz** [comment]
@Beej126 Currently i switched back to sharpshell. Now it works correctly after startup (without restart of `Explorer.exe` after Windows login) but it is very important that UI updates come with a little bit of delay. Otherwise the component crashed.

**Comment by Beej126** [comment]
@lutz thanks for update... i have notes that remind me i left sharpshell because it was winforms only and i am keen on wpf databinding, admittedly a pretty small use of it.

**Comment by lutz** [comment]
Hello @Beej126 
that seems to be right. I switched back after i found out that transparency is also possible with sharpshell. WinForms is (you see it at the very easy code :D) enough in this context. Currently the timer option is pretty nerd but i had not the time to look at https://github.com/Grabacr07/SylphyHorn which has an implementation of an vd currentchanged event.
