### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by bfcns** [lutz/VirtualDesktopNameDeskband#3]
Is this possible in Windows 11?

**Comment by lutz** [comment]
@phpcitizen Currently it didn't work under Windows 11. The problem is that windows 11 comes with lot of changes to the taskbar and it seems to be that Microsoft cancel the feature for Deskband support.

**Comment by bfcns** [comment]
Thanks for the reply. Yes indeed.
Can you please check [ElevenClock](https://github.com/martinet101/ElevenClock)
It seems to be built on Python though, but it might give some insight what you can do for Windows 11.

**Comment by lutz** [comment]
@phpcitizen Sorry but i have currently no time for researching. I use a component called [SharpShell](https://github.com/dwmkerr/sharpshell) for deskband injecting. So feel free to ask there for supporting deskband under windows 11. If it possible so i can also support it.
