### ISSUE TITLE
.exe installer

### ISSUE THREAD

**Issue by 4rafi** [lutz/VirtualDesktopNameDeskband#4]
hey i know that is been a while since this project is maintained. i just wanted to ask if its possible to you to provide a installer .exe file for this project, im not that tech savvy and still happy stuck with win10. its okay if you dont have the time, i just asking just in case its possible.
Thank you for your consideration.

**Comment by lutz** [comment]
Hello @4rafi currently i have no time to provide an installer for this project. The repository contains all introductions to clone, create the strong name ( with Visual Studio COmmunity), build and regsiter.
Best regards
